# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('str', 'str'), ('int', 'int'), ('float', 'float')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microbial_growth_data.Design')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentalDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designElements', models.ManyToManyField(blank=True, to='microbial_growth_data.DesignElement')),
            ],
        ),
        migrations.CreateModel(
            name='Experimenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('dataFile', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('cleanedData', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('experimenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microbial_growth_data.Experimenter')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('dataStarted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subarticles', to='microbial_growth_data.Strain')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('biologicalReplicate', models.IntegerField(default=0)),
                ('experimentalDesign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='microbial_growth_data.ExperimentalDesign')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microbial_growth_data.Plate')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microbial_growth_data.Project'),
        ),
        migrations.AddField(
            model_name='experimentaldesign',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microbial_growth_data.Strain'),
        ),
    ]
