# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthData', '0004_auto_20151210_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
