# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designelement',
            old_name='strain',
            new_name='design',
        ),
        migrations.AddField(
            model_name='plate',
            name='name',
            field=models.CharField(default='ura3 control', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
