# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthData', '0002_auto_20151209_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='biologicalReplicate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='technicalReplicate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
