# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growthData', '0005_auto_20151210_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growthData.Strain')),
            ],
        ),
        migrations.AlterField(
            model_name='experimentaldesign',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growthData.Strain'),
        ),
    ]
